# Generated by Django 4.1.2 on 2022-10-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user_2", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("t", "Teacher"), ("s", "Student")], max_length=7
            ),
        ),
    ]
