# Generated by Django 4.1.2 on 2022-10-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user_2", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("teacher", "teacher"), ("student", "student")], max_length=7
            ),
        ),
    ]
